### ISSUE TITLE
Game freezes if you use quick save/load 

### ISSUE THREAD

**Issue by foxyoverdrive** [YaLTeR/BunnymodXT#26] opened 2017-07-16 11:47 UTC
I'm practicing in TestChamber Skip with the object boost from the cart. If I use BXT I get freeze and then crash after few attempts to use quick load.

**Comment by YaLTeR** [comment] 2017-07-16 11:58
Huh, weird. What exactly are you doing?

**Comment by foxyoverdrive** [comment] 2017-07-16 12:13
Well, I guess you know about the last test chamber skip.. :) So I get into position, aim on the cart, quick save, object boost, quick load, object boost, quick load, object boost until I get 1800+ speed. And randomly after few attempts my game freezes with the "LOADGING" at the center of the screen then crashes.

**Comment by YaLTeR** [comment] 2017-07-16 13:05
Well, I can't see where the problem could be immediately.

**Comment by foxyoverdrive** [comment] 2017-07-16 13:42
Just let me know if I can help you with some things such as crashlogs or something

**Comment by YaLTeR** [comment] 2017-07-16 14:39
The problem is there isn't really any crash report system in place. We could try to do some debugging, but it would be better if you contacted me elsewhere for that, for example in [Discord](https://discord.gg/sourceruns).

**Comment by YaLTeR** [comment] 2017-08-10 21:12
After some discussion, the crashes happen even without BXT. Closing for now.

**Closed by YaLTeR** 2017-08-10 21:12 UTC
